# Generated by Django 3.2.9 on 2021-11-25 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True, unique=True, verbose_name='Бренд')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True, unique=True, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='ItemUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=300, null=True, verbose_name='Ссылка на страницу товара')),
            ],
            options={
                'verbose_name': 'Ссылка на товар',
                'verbose_name_plural': 'Ссылки на товар',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True, unique=True, verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True, verbose_name='Название товара')),
                ('image_url', models.CharField(blank=True, max_length=300, null=True, verbose_name='Ссылка на изображение')),
                ('vendor_code', models.IntegerField(blank=True, null=True, verbose_name='Артикул')),
                ('rating', models.IntegerField(blank=True, null=True, verbose_name='Рейтинг')),
                ('reviews', models.IntegerField(blank=True, null=True, verbose_name='Количество отзывов')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена без скидки')),
                ('price_with_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена со скидкой')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='Доступно')),
                ('quantity_of_purchased', models.IntegerField(blank=True, null=True, verbose_name='Количество покупок')),
                ('revenue', models.IntegerField(blank=True, null=True, verbose_name='Выручка')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_panel.brand', verbose_name='Бренд')),
                ('categories', models.ManyToManyField(blank=True, null=True, to='data_panel.Category', verbose_name='Категории')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_panel.provider', verbose_name='Поставщик')),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_panel.itemurl', verbose_name='Ссылка на страницу товара')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
