# Generated by Django 3.2.9 on 2021-11-10 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=300, null=True)),
                ('name', models.CharField(max_length=300)),
                ('image_url', models.CharField(max_length=300)),
                ('url', models.CharField(max_length=300)),
                ('brand', models.CharField(max_length=300)),
                ('vendor_code', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('reviews', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_with_discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('categories', models.CharField(max_length=500)),
                ('quantity_of_purchased', models.IntegerField()),
                ('revenue', models.IntegerField()),
            ],
        ),
    ]
