# Generated by Django 3.2.9 on 2021-11-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterField(
            model_name='item',
            name='brand',
            field=models.CharField(max_length=300, verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='item',
            name='categories',
            field=models.CharField(max_length=500, verbose_name='Рубрики'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_url',
            field=models.CharField(max_length=300, verbose_name='Ссылка на изображение'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Название товара'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена без скидки'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price_with_discount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена со скидкой'),
        ),
        migrations.AlterField(
            model_name='item',
            name='provider',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(verbose_name='Доступно'),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity_of_purchased',
            field=models.IntegerField(verbose_name='Количество покупок'),
        ),
        migrations.AlterField(
            model_name='item',
            name='rating',
            field=models.IntegerField(verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='item',
            name='revenue',
            field=models.IntegerField(blank=True, null=True, verbose_name='Выручка'),
        ),
        migrations.AlterField(
            model_name='item',
            name='reviews',
            field=models.IntegerField(verbose_name='Количество отзывов'),
        ),
        migrations.AlterField(
            model_name='item',
            name='url',
            field=models.CharField(max_length=300, verbose_name='Ссылка на страницу товара'),
        ),
        migrations.AlterField(
            model_name='item',
            name='vendor_code',
            field=models.IntegerField(verbose_name='Артикул'),
        ),
    ]
