# Generated by Django 3.2.9 on 2021-11-11 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_panel', '0002_auto_20211112_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена без скидки'),
        ),
    ]
