# Generated by Django 3.2.9 on 2021-11-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_panel', '0003_item_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='revenue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=35, null=True, verbose_name='Выручка'),
        ),
    ]
