# Generated by Django 3.2.9 on 2021-11-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_panel', '0003_alter_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
