# Generated by Django 3.2.9 on 2021-11-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_panel', '0004_alter_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='brand',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='item',
            name='categories',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Рубрики'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_url',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Ссылка на изображение'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Название товара'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price_with_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена со скидкой'),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Доступно'),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity_of_purchased',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество покупок'),
        ),
        migrations.AlterField(
            model_name='item',
            name='rating',
            field=models.IntegerField(blank=True, null=True, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='item',
            name='reviews',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество отзывов'),
        ),
        migrations.AlterField(
            model_name='item',
            name='url',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Ссылка на страницу товара'),
        ),
        migrations.AlterField(
            model_name='item',
            name='vendor_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Артикул'),
        ),
    ]
